// seednr-web — Model Type Definitions (JSDoc)
// Auto-generated by parse-schema.js from schema/schema.xml
// Re-generate: npm run parse-schema
//
// Usage: reference these types in your JS files with:
//   /** @type {Contact} */
//   var contact = records[0];

/**
 * @typedef {Object} Affiliation
 * @property {number} id
 * @property {number} [created_at] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 */

/**
 * A Product represents a digital or physical good available for purchase.
 * @typedef {Object} Product
 * @property {number} id
 * @property {number} [created_at] - unix timestamp
 * @property {string} [delay_start]
 * @property {boolean} [deleted]
 * @property {string} [description]
 * @property {string} [download_limit]
 * @property {string} [download_time_limit]
 * @property {string} [external_id] - ID in external integrations
 * @property {string} [internal_name] - name for internal use, not visible to purchasers
 * @property {number} [last_modified_at] - unix timestamp
 * @property {string} [level1] - The commission tier paid to level 1 Affiliates.
 * @property {string} [level2] - The commission tier paid to level 2 Affiliates.
 * @property {boolean} [offer_to_affiliates]
 * @property {number} [price] - currency
 * @property {string} [product_code] - code for internal identification
 * @property {string} [product_group]
 * @property {string} [product_type]
 * @property {string} [public_name]
 * @property {number} [revenue] - currency
 * @property {number} [setup_fee] - currency
 * @property {string} [setup_fee_date]
 * @property {string} [setup_fee_when]
 * @property {string} [shipping]
 * @property {string} [sku]
 * @property {string} [subscription_count]
 * @property {number} [subscription_fee] - currency
 * @property {string} [subscription_unit]
 * @property {boolean} [taxable]
 * @property {number} [total_purchases_count] - Ongoing total count of purchases
 * @property {number} [trial_period_count]
 * @property {string} [trial_period_unit]
 * @property {number} [trial_price] - currency
 * @property {string} [type]
 */

/**
 * A Tag is a way to label and group related objects, much like a category or segment. For example, a Tag could be assigned to Contacts when they fill out a particular Form. Tags are useful for performin
 * @typedef {Object} Tag
 * @property {number} tag_id
 * @property {string} [name] - The name of the tag.
 * @property {number} [object_type_id] - The ID of the type of object (aka \
 */

/**
 * A Message represents an Email that is sent as part of a Blast (one-off send), a Sequence (autoresponder), or both. There will be ObjectLogEntry records for each Contact that the Message is sent to tha
 * @typedef {Object} Message
 * @property {number} id
 * @property {string} [autosave] - The content of the last autosave.
 * @property {number} [clicked_count]
 * @property {number} [complaints_count]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [from]
 * @property {string} [json_data] - The content of an ONTRAmail message.
 * @property {number} [last_auto] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [last_save] - unix timestamp
 * @property {string} [message_body] - For legacy emails only, the HTML content of the message.
 * @property {string} [name] - The message name.
 * @property {number} [not_clicked_count]
 * @property {number} [not_opened_count] - The number of contacts that have not opened the message.
 * @property {number} [object_type_id] - The ID of the type of object (aka \
 * @property {string} [old_resource]
 * @property {number} [opened_count] - The number of contacts that have opened the message.
 * @property {string} [plaintext]
 * @property {string} [reply_to_email] - The \
 * @property {Object} [resource]
 * @property {string} [send_from_email]
 * @property {string} [send_out_name]
 * @property {string} [send_to]
 * @property {number} [sent_count] - The number of contacts the message was sent to.
 * @property {string} [site_id]
 * @property {number} [spam_score]
 * @property {string} [subject] - The email subject line.
 * @property {boolean} [transactional_email]
 * @property {'Email'|'Email (Transactional)'|'Email/ONTRAmail'|'ONTRAmail'|'ONTRAmail (Transactional)'|'Postcard'|'SMS'|'Simple Mail'|'Simple Mail (Transactional)'|'Task Template'} [type] - The message type.
 * @property {number} [unsubscribed_count]
 * @property {string} [utm_tracking]
 * @property {string} [word_wrap_checkbox]
 */

/**
 * @typedef {Object} Note
 * @property {number} id
 * @property {number} [Affiliation_id] - FK → Affiliation
 * @property {number} [Comm_id] - FK → Comm
 * @property {number} [Contact_id] - FK → Contact
 * @property {number} [Organisation_id] - FK → Organisation
 * @property {number} [date_created] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 * @property {string} [note]
 * @property {number} [object_id]
 * @property {number} [object_type_id] - The ID of the type of object (aka \
 * @property {'API'|'Form'|'Incoming'|'Manual'|'Outgoing'} [type]
 */

/**
 * @typedef {Object} Organisation
 * @property {number} id
 * @property {string} [xero_id]
 * @property {string} [hubspotid]
 * @property {string} [last_note]
 * @property {string} [unique_id]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [ip_address]
 * @property {number} [last_activity] - unix timestamp
 * @property {number} [last_sms_sent] - unix timestamp
 * @property {string} [profile_image] - image URL
 * @property {number} [last_email_sent] - unix timestamp
 * @property {number} [last_call_logged] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [last_sms_received] - unix timestamp
 * @property {number} [last_email_received] - unix timestamp
 * @property {string} [city]
 * @property {string} [name]
 * @property {string} [phone]
 * @property {string} [state]
 * @property {string} [address]
 * @property {string} [website] - Url/path
 * @property {'Accounting'|'Apparel & Fashion'|'Automotive'|'Banking'|'Computer Software'|'Construction'|'Design'|'Education'|'Engineering'|'Environmental Services'|'Finance'|'Food & Beverages'|'Food + Agriculture'|'Food Production'|'Government Administration'|'Healthcare'|'Higher Education'|'Hospitality'|'Individual & Family Services'|'Information Technology and Services'|'Insurance'|'Legal Services'|'Leisure, Travel & Tourism'|'Manufacturing'|'Maritime'|'Marketing + Advertising'|'Non-Profit Organization Management'|'Pharma'|'Photography'|'Primary/Secondary Education'|'Printing'|'Professional Training & Coaching'|'Real Estate'|'Renewables & Environment'|'Restaurant'|'Retail'|'Software'|'Telecommunications'|'Transport'|'Wellness and Fitness'|'Wholesale'} [industry]
 * @property {string} [legal_name]
 * @property {string} [description]
 * @property {string} [postal_code]
 * @property {string} [facebook_page]
 * @property {'1m - 5m'|'20m - 50m'|'50m - 100m'|'5m - 20m'|'< 1m'|'> 100m'} [annual_revenue]
 * @property {string} [instagram_name]
 * @property {string} [linked_in_page] - Url/path
 * @property {string} [twitter_handle]
 * @property {string} [reference_number]
 * @property {string} [you_tube_channel] - Url/path
 * @property {number} [billing_contact_id] - FK → Affiliation
 * @property {number} [primary_contact_id] - FK → Affiliation
 * @property {'10 - 50'|'1000 +'|'200 - 1000'|'50 - 200'|'< 10'} [number_of_employees]
 * @property {string} [reference_number_type]
 * @property {string} [logo] - image URL
 * @property {'Active'|'Application'|'Ex-Member'|'On Boarding'|'Suspended'} [status]
 * @property {number} [date_joined] - unix timestamp
 * @property {string} [current_month]
 * @property {string} [profile_summary]
 * @property {string} [org_button_image] - image URL
 * @property {string} [last_xero_invoice]
 * @property {'Completed'|'Error'|'Processing'} [invoice_creation_status]
 * @property {boolean} [generate_prorata_invoice]
 * @property {boolean} [create_next_annual_invoice]
 * @property {number} [date_paid_last_membership_fee] - unix timestamp
 * @property {string} [portal_affiliation_management_url]
 * @property {number} [portal_affiliation_management_visits]
 * @property {boolean} [portal_affiliation_management_published]
 * @property {number} [portal_affiliation_management_unique_visits]
 * @property {'Pay by Credit/Debit Card'|'Pay on Invoice'} [payment_method]
 * @property {string} [other_questions]
 * @property {'Community Group'|'Company Limited by Guarantee'|'Indigenous Corporation'|'Individual Project'|'NSW Incorporated Association'|'Not-for-profit Company'|'Not-for-profit Organisation'|'QLD Incorporated Association'|'Sole Trader'} [type_of_organisation]
 * @property {number} [date_expressed_interest] - unix timestamp
 * @property {boolean} [acknowledge_membership_fee]
 * @property {string} [description_of_organisation]
 * @property {string} [other]
 * @property {boolean} [support_letter]
 * @property {boolean} [authority_to_fundraise]
 * @property {boolean} [grant_writing_services]
 * @property {boolean} [access_to_grant_databases]
 * @property {boolean} [project_management_advice]
 * @property {boolean} [skill_development_workshops]
 * @property {boolean} [organisational_development_resources]
 * @property {boolean} [promotional_support_of_your_activities]
 * @property {boolean} [support_in_forming_a_workers_co_operative]
 * @property {boolean} [support_to_become_an_incorporated_association]
 * @property {boolean} [marketing_community_engagement_strategy_brainstorm]
 * @property {boolean} [potential_discount_on_insurance_coverage_for_volunteers]
 * @property {boolean} [support_to_manage_reporting_and_record_keeping_obligations]
 * @property {boolean} [a_personalised_segment_on_the_seed_website_that_links_to_your_we]
 * @property {boolean} [access_to_grants_and_donations_requiring_dgr_deductible_gift_rec]
 * @property {boolean} [exploring_access_to_a_site_at_the_mullum_enterprise_gardens_for_]
 * @property {boolean} [i_d_like_my_project_to_become_a_mullum_seed_project_i_m_not_inco]
 * @property {boolean} [networking_peer_to_peer_skill_development_with_other_environment]
 * @property {boolean} [support_to_register_as_a_charity_and_or_environmental_organisati]
 * @property {boolean} [a_intergenerational_equity]
 * @property {boolean} [c_biodiversity_conservation]
 * @property {boolean} [b_the_precautionary_approach]
 * @property {boolean} [sustainable_development_object_n_a]
 * @property {boolean} [d_supporting_the_relocalisation_of_goods_and_services_within_the]
 * @property {boolean} [research_programme_object_n_a]
 * @property {boolean} [a_soil_biology_and_the_relationship_between_healthy_ecosystems_a]
 * @property {boolean} [b_practices_and_technologies_for_the_rejuvenation_and_improvemen]
 * @property {boolean} [c_monitoring_on_site_water_use_and_grey_water_management_to_mini]
 * @property {boolean} [d_the_compatibility_of_particular_plants_soil_types_and_climatic]
 * @property {boolean} [b_waste_minimisation]
 * @property {boolean} [education_objects_n_a]
 * @property {boolean} [d_water_conservation_and_reuse_systems]
 * @property {boolean} [a_the_role_of_soil_health_in_maintaining_sustainable_ecosystems]
 * @property {boolean} [g_demonstrate_best_practice_sustainable_design_and_technologies]
 * @property {boolean} [c_modelling_a_variety_of_composting_methods_that_utilise_waste_m]
 * @property {boolean} [e_the_identification_and_management_of_weed_species_incorporatin]
 * @property {boolean} [f_the_sustainable_production_of_food_in_a_manner_that_enhances_t]
 * @property {boolean} [application_objects_n_a]
 * @property {boolean} [a_the_enhancement_of_the_natural_environment]
 * @property {boolean} [b_the_optimisation_of_environmentally_sustainable_food_productio]
 * @property {boolean} [c_community_capacity_building_that_empowers_people_to_integrate_]
 * @property {boolean} [d_create_an_inclusive_environment_which_enables_people_of_all_ag]
 * @property {string} [member_expression_of_interest_url]
 * @property {number} [member_expression_of_interest_visits]
 * @property {boolean} [member_expression_of_interest_published]
 * @property {number} [member_expression_of_interest_unique_visits]
 * @property {boolean} [create_qr]
 * @property {'Expanded Template'|'Own Link'|'Standard Simple'} [donation_template]
 * @property {string} [member_donation_url]
 * @property {string} [biline_donation_page]
 * @property {string} [content_donation_page]
 * @property {string} [donation_page_qr_code] - image URL
 * @property {string} [external_donation_link] - Url/path
 * @property {number} [member_donation_visits]
 * @property {string} [background_donation_page] - image URL
 * @property {boolean} [member_donation_published]
 * @property {number} [member_donation_unique_visits]
 * @property {string} [gateway_id]
 * @property {string} [invoice_id]
 * @property {string} [product_id]
 * @property {boolean} [create_gateway]
 * @property {boolean} [create_product]
 * @property {string} [member_onboarding_url]
 * @property {number} [member_onboarding_visits]
 * @property {boolean} [member_onboarding_published]
 * @property {number} [member_onboarding_unique_visits]
 * @property {string} [bsb]
 * @property {string} [account]
 * @property {'I need a bank account from Mullum SEED'|'My org is setting up a bank account still'|'Use the bank details below'} [bank_status]
 * @property {string} [sign_wellid]
 * @property {string} [signing_url]
 * @property {string} [account_name]
 * @property {boolean} [auspiced_by_seed]
 * @property {'Application Under Review'|'Auspice Agreement Completed'|'Awaiting Auspice Agreement Completion'|'Awaiting Gateway Connection'|'Awaiting Invoice Creation'|'Awaiting Org Info'|'Awaiting Product Creation'|'Awaiting Stripe Setup'|'Cancelled'|'Declined'|'New'|'On Hold'|'Ready for Donations'|'Renew Agreement'} [donations_status]
 * @property {number} [date_start_auspice] - unix timestamp
 * @property {number} [date_auspice_signed] - unix timestamp
 * @property {number} [date_expire_auspice] - unix timestamp
 * @property {number} [date_review_auspice] - unix timestamp
 * @property {string} [project_description]
 * @property {string} [donation_receipt_code]
 * @property {string} [name_of_auspice_project]
 * @property {string} [signed_auspice_agreement] - Url/path
 * @property {boolean} [re_create_unsigned_agreement_use_sparingly]
 * @property {'Not insured with SEED'|'SEED'|'SEED public liability only'} [insurance_cover]
 * @property {number} [date_end_insurance] - unix timestamp
 * @property {number} [date_start_insurance] - unix timestamp
 * @property {string} [drive_folderid]
 * @property {string} [drive_folder_link] - Url/path
 * @property {boolean} [create_member_drive_folder]
 * @property {string} [section_image1] - image URL
 * @property {string} [section_image2] - image URL
 * @property {string} [our_purpose_text]
 * @property {string} [our_purpose_image1] - image URL
 * @property {string} [our_purpose_image2] - image URL
 * @property {string} [our_purpose_image3] - image URL
 * @property {string} [what_you_can_do_cta]
 * @property {string} [what_you_can_do_link] - Url/path
 * @property {string} [what_you_can_do_text]
 * @property {string} [what_we_are_doing_text]
 * @property {string} [lower_feature_background] - image URL
 * @property {string} [portal_profile_url]
 * @property {number} [portal_profile_visits]
 * @property {boolean} [portal_profile_published]
 * @property {number} [portal_profile_unique_visits]
 * @property {string} [portal_auspice_url]
 * @property {number} [portal_auspice_visits]
 * @property {boolean} [portal_auspice_published]
 * @property {number} [portal_auspice_unique_visits]
 * @property {string} [member_gift_notification_url]
 * @property {number} [member_gift_notification_visits]
 * @property {boolean} [member_gift_notification_published]
 * @property {number} [member_gift_notification_unique_visits]
 * @property {string} [member_needs_and_objects_url]
 * @property {number} [member_needs_and_objects_visits]
 * @property {boolean} [member_needs_and_objects_published]
 * @property {number} [member_needs_and_objects_unique_visits]
 * @property {string} [portal_rff_url]
 * @property {number} [portal_rff_visits]
 * @property {boolean} [portal_rff_published]
 * @property {number} [portal_rff_unique_visits]
 * @property {number} [fund_request_count_all]
 * @property {string} [fund_request_open_total]
 * @property {string} [offline_donations_pending]
 * @property {string} [offline_donations_received]
 * @property {string} [portal_bank_details_url]
 * @property {number} [portal_bank_details_visits]
 * @property {boolean} [portal_bank_details_published]
 * @property {number} [portal_bank_details_unique_visits]
 * @property {string} [portal_member_donation_page_edits_url]
 * @property {number} [portal_member_donation_page_edits_visits]
 * @property {boolean} [portal_member_donation_page_edits_published]
 * @property {number} [portal_member_donation_page_edits_unique_visits]
 * @property {number} [next_board_meeting_date] - unix timestamp
 * @property {number} [next_board_meeting_time] - unix timestamp
 * @property {'Closed'|'Open'} [board_agenda_item_status]
 * @property {string} [portal_impact_reports_url]
 * @property {number} [portal_impact_reports_visits]
 * @property {boolean} [portal_impact_reports_published]
 * @property {number} [portal_impact_reports_unique_visits]
 * @property {boolean} [bruns_river_keepers_founding_members]
 * @property {boolean} [bruns_river_keepers_partners_supporters]
 * @property {string} [seed_northern_rivers_member_donation_url]
 * @property {number} [seed_northern_rivers_member_donation_visits]
 * @property {boolean} [seed_northern_rivers_member_donation_published]
 * @property {number} [seed_northern_rivers_member_donation_unique_visits]
 * @property {string} [menu_link_name]
 * @property {boolean} [show_as_project]
 * @property {boolean} [show_as_campaign]
 * @property {string} [link_to_content_in_menu] - Url/path
 */

/**
 * A TagSubscriber relates an object to a Tag, signifying the object has been assigned the particular Tag.
 * @typedef {Object} TagSubscriber
 * @property {number} id
 * @property {number} [Affiliation_id] - FK → Affiliation
 * @property {number} [Comm_id] - FK → Comm
 * @property {number} [Contact_id] - FK → Contact
 * @property {number} [Organisation_id] - FK → Organisation
 * @property {number} [tag_id] - FK → Tag
 * @property {number} [object_id]
 * @property {number} [object_type_id]
 */

/**
 * @typedef {Object} Contact
 * @property {number} id
 * @property {string} [fax] - Phone/SMS number
 * @property {string} [city]
 * @property {string} [role]
 * @property {string} [email]
 * @property {string} [state]
 * @property {string} [title]
 * @property {string} [address]
 * @property {string} [country] - Country ISO 3166-1 alpha-2 code (2 character)
 * @property {string} [profile] - image URL
 * @property {string} [website] - Url/path
 * @property {number} [birthday] - unix timestamp
 * @property {string} [zip_code]
 * @property {string} [address_2]
 * @property {string} [last_name]
 * @property {number} [company_id] - FK → Organisation
 * @property {string} [first_name]
 * @property {string} [sms_number]
 * @property {string} [company_name]
 * @property {string} [office_phone]
 * @property {number} [affiliation_count]
 * @property {string} [linkedin_profile_url]
 * @property {boolean} [i_agree_to_receive_communications_from_mullum_seed_inc]
 * @property {string} [spent]
 * @property {string} [twitter]
 * @property {string} [facebook]
 * @property {string} [linkedin]
 * @property {string} [timezone] - IANA time zone, ex: America/New_York
 * @property {string} [hubspotid]
 * @property {string} [instagram]
 * @property {string} [last_note]
 * @property {string} [unique_id]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [ip_address]
 * @property {string} [user_agent]
 * @property {number} [last_activity] - unix timestamp
 * @property {number} [last_sms_sent] - unix timestamp
 * @property {number} [last_email_sent] - unix timestamp
 * @property {number} [last_call_logged] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [last_sms_received] - unix timestamp
 * @property {number} [last_email_received] - unix timestamp
 * @property {string} [gclid]
 * @property {number} [score]
 * @property {'High'|'Low'|'Medium'} [priority]
 * @property {'Closed - Lost'|'Closed - Won'|'Committed'|'Consideration'|'Demo Scheduled'|'New Prospect'|'Qualified Lead'} [sales_stage]
 * @property {string} [facebook_fbc]
 * @property {string} [facebook_fbp]
 * @property {string} [ga_client_id]
 * @property {string} [media_medium]
 * @property {string} [ga_session_id]
 * @property {string} [referring_page]
 * @property {boolean} [bulk_sms_status]
 * @property {boolean} [bulk_email_status]
 * @property {string} [ga_session_number]
 * @property {'Converted Member'|'Engaged Interest'|'Initiated Contact'|'Leads'|'Negotiation Commitment'|'Proposal Sent'} [members_prospects]
 * @property {string} [linked_in_click_id]
 * @property {'More than a month ago (Cold)'|'This Week'|'This month'|'Today (Hot!)'} [time_since_last_activity]
 * @property {string} [last_inbound_sms]
 * @property {string} [job_title]
 * @property {string} [hubspot_comment]
 * @property {string} [donation_preference]
 * @property {string} [tell_us_more]
 * @property {string} [profile_image] - image URL
 * @property {string} [tell_us_more_2]
 * @property {'By Physical help'|'Others'|'With Cash'} [how_can_we_help]
 * @property {number} [amount]
 * @property {string} [member]
 * @property {boolean} [monthly]
 * @property {boolean} [once_off]
 * @property {string} [gateway_id]
 * @property {string} [invoice_id]
 * @property {string} [product_id]
 * @property {'New'|'Processing'|'Success'} [donation_status]
 * @property {'Maybe'|'Not Right Now'|'Yes'} [mentorship_interest]
 * @property {string} [giving_circle_inspiration]
 * @property {number} [last_invoice]
 * @property {string} [offline_transfers]
 * @property {number} [last_charge_amount] - currency
 * @property {number} [last_total_invoice_amount] - currency
 * @property {number} [total_amount_of_unpaid_transactions] - currency
 * @property {'[object Object]'|'American Express'|'Discover'|'Mastercard'|'Other'|'Paypal'|'Visa'} [last_card_type]
 * @property {'[object Object]'|'Declined'|'Success'} [last_cc_status]
 * @property {string} [last_card_number_last_4]
 * @property {number} [last_card_expiration_date] - unix timestamp
 * @property {number} [last_card_expiration_year]
 * @property {'April'|'August'|'December'|'February'|'January'|'July'|'June'|'March'|'May'|'November'|'October'|'September'} [last_card_expiration_month]
 * @property {boolean} [lives_on_the_brunswick_river]
 * @property {boolean} [plays_on_the_brunswick_r_iver]
 * @property {string} [vision_for_the_brunswick_river]
 * @property {'Children’s activities'|'Citizen science/river health monitoring'|'Donating to the cause'|'Education and workshops'|'Events'|'Fundraising'|'Tree planting'} [is_keen_to_assist_or_participate_with]
 * @property {boolean} [wishes_to_volunteer_to_assist_the_alliance]
 * @property {string} [has_the_following_skills_or_experience_that_they_can_offer_to_th]
 * @property {Object} [insurance]
 * @property {string} [vendor_name]
 * @property {number} [stall_amount] - currency
 * @property {'Card Added'|'Processing'|'Success'} [payment_status]
 * @property {number} [donation_amount] - currency
 * @property {'Extra Large - > 6 m x 10 m $155.00 + GST'|'Extra Small - 2m x 2m= 4m2  $40.00 + GST'|'Govt Org: Large - 6m x 6m = 36 m2 $160.00  + GST'|'Govt Org: Medium - 3m x 6m = 18 m2 $130.00 + GST'|'Govt Org: Small - 3m x3 m = 9m2 $100.00 + GST'|'Large - 6m x 6m = 36 m2 $115.00  + GST'|'Medium - 3m x 6m = 18 m2 $85.00 + GST'|'Small - 3m x3 m = 9m2 $55.00 + GST'} [stall_selection]
 * @property {string} [about_your_stall]
 * @property {boolean} [terms_conditions]
 * @property {number} [date_signed_terms] - unix timestamp
 * @property {string} [plants_you_sell_options_as_text] - This field represents a \
 * @property {string} [location_plants_grown_options_as_text] - This field represents a \
 * @property {boolean} [i_agree_with_all_the_terms_of_service_and_privacy_policy]
 * @property {'Monthly'|'One Time'} [donation_type]
 * @property {'$100'|'$1000'|'$50'|'Other'} [select_amount]
 * @property {number} [donation_amounts] - currency
 * @property {string} [giving_circle_comment]
 * @property {number} [gift_amount] - currency
 * @property {string} [gift_message]
 * @property {number} [transfer_date] - unix timestamp
 * @property {boolean} [send_me_email_updates]
 * @property {boolean} [send_me_updates_in_text_messages]
 * @property {boolean} [brunsrk_subscribe]
 * @property {boolean} [brunsrk_volunteer]
 * @property {boolean} [brunsrk_membership]
 * @property {'Get membership and become a riverkeeper .'|'Subscribe to stay updated .'|'Volunteer'} [select_your_intreest]
 * @property {boolean} [boating]
 * @property {boolean} [fishing]
 * @property {boolean} [swimming]
 * @property {string} [municipality]
 * @property {boolean} [mention_other]
 * @property {boolean} [donating_funds]
 * @property {string} [mention_others]
 * @property {boolean} [attending_events]
 * @property {boolean} [other_activities]
 * @property {boolean} [other_recreation]
 * @property {string} [other_activities_explain]
 * @property {boolean} [participating_in_educational_workshops]
 * @property {string} [if_the_river_had_a_voice_what_would_it_say]
 * @property {boolean} [discussing_a_corporate_partnership_or_sponsorship]
 * @property {'No'|'Yes'} [do_you_live_or_work_in_the_brunswick_river_catchment]
 * @property {boolean} [learning_more_about_indigenous_connections_to_the_river]
 * @property {boolean} [i_m_not_sure_yet_just_keep_me_updated_on_what_is_happening]
 * @property {string} [which_bruns_riverkeepers_member_group_s_are_you_part_of_if_any]
 * @property {boolean} [discussing_my_property_as_a_location_for_tree_planting_and_other]
 * @property {boolean} [participating_in_the_healthy_rivers_monitoring_program_and_citiz]
 * @property {boolean} [weed_management]
 * @property {boolean} [riparian_revegetation]
 * @property {boolean} [make_a_financial_contribution]
 * @property {boolean} [addressing_erosion_of_river_banks]
 * @property {boolean} [fencing_my_creek_to_exclude_grazing]
 * @property {boolean} [planting_native_trees_reforestation]
 * @property {boolean} [i_would_like_to_become_a_riverkeeper]
 * @property {boolean} [habitat_and_threatened_species_restoration]
 * @property {boolean} [undertake_catchment_restoration_works_on_my_property]
 * @property {boolean} [i_would_like_my_organization_or_business_to_join_the_riverkeeper]
 * @property {'No'|'Yes'} [would_you_like_more_information_on_river_restoration_works_on_yo]
 * @property {boolean} [i_would_like_to_volunteer_as_a_researcher]
 * @property {string} [i_have_the_following_skills_and_capacities_to_offer]
 * @property {boolean} [i_would_like_to_volunteer_in_organizing_events_and_admin]
 * @property {boolean} [i_am_an_artist_and_would_like_to_perform_or_create_works_for_the]
 * @property {boolean} [i_would_like_to_volunteer_for_on_ground_action_tree_planting_or_]
 * @property {'Care for the river'|'Celebrate the river'|'Connect to the river'} [involvement_type]
 * @property {number} [ask_amount] - currency
 * @property {string} [key_people]
 * @property {string} [past_giving]
 * @property {number} [follow_up_date] - unix timestamp
 * @property {'Contacts to other funders'|'Corporate partnerships'|'Foundations'|'High net worth individuals'|'Hub to funders'} [type_of_funder]
 * @property {number} [committed_amount] - currency
 * @property {string} [important_to_note]
 * @property {string} [engagement_procedure]
 * @property {number} [probability_of_success]
 * @property {string} [funder_area_of_interest]
 * @property {'Bruns River'|'Changemakers'|'Infrastructure'} [program_seeking_funding]
 * @property {number} [expected_commitment_date] - unix timestamp
 * @property {'Continued Engagement'|'Donation Received'|'Initiated Contact'|'Meeting undertaken'|'Negotiating Donation'|'New Prospect'|'Not a prospect'|'Qualifying Lead'|'Scheduling a meeting'} [philanthropic_engagement_status]
 * @property {string} [interactions_with_seed_nr_to_date]
 * @property {string} [details]
 * @property {string} [location]
 * @property {number} [date_time] - unix timestamp
 * @property {string} [upload_photo] - image URL
 * @property {number} [affiliation_as_active_members]
 * @property {'Across the Northern Rivers'|'Ballina'|'Byron'|'Clarence'|'Kyogle'|'LGA'|'Lismore'|'Richmond'|'Tweed'} [lga]
 * @property {'Academia'|'Business'|'Community/Not for proft'|'Government'|'Philanthropy'|'Sector'} [sector]
 * @property {'Both'|'INR'|'SNR'} [source_of_lead]
 * @property {boolean} [contact_re_survey]
 * @property {'Arts/culture'|'Business development'|'Community engagement'|'Disability'|'Education'|'Environment'|'Food & ag'|'Indigenous'|'Issues of interest'|'Resilience'|'Social - housing, poverty, health, crime'|'Women'|'Youth'} [issue_of_interest]
 * @property {string} [Total_Donated]
 * @property {string} [Giving_Circle_Donated]
 * @property {number} [date_became_giving_circle_member] - unix timestamp
 * @property {string} [giving_portal_invoices_url]
 * @property {number} [giving_portal_invoices_visits]
 * @property {boolean} [giving_portal_invoices_published]
 * @property {number} [giving_portal_invoices_unique_visits]
 * @property {string} [giving_portal_project_voting_url]
 * @property {number} [giving_portal_project_voting_visits]
 * @property {boolean} [giving_portal_project_voting_published]
 * @property {number} [giving_portal_project_voting_unique_visits]
 * @property {boolean} [admin]
 * @property {boolean} [voter]
 * @property {boolean} [applicant]
 * @property {boolean} [committee]
 * @property {'active'|'success'|'suspended'|'updating'} [grants_app_status]
 * @property {string} [grants_app_user_uuid]
 */

/**
 * @typedef {Object} Comm
 * @property {number} id
 * @property {string} [last_note]
 * @property {string} [unique_id]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [ip_address]
 * @property {number} [last_activity] - unix timestamp
 * @property {number} [last_sms_sent] - unix timestamp
 * @property {string} [profile_image] - image URL
 * @property {number} [last_email_sent] - unix timestamp
 * @property {number} [last_call_logged] - unix timestamp
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [last_sms_received] - unix timestamp
 * @property {number} [last_email_received] - unix timestamp
 * @property {'Board Comms'|'Gift Notification'|'Impact Report'|'Member Support'|'Request For Funds'} [type]
 * @property {number} [organisation_id] - FK → Organisation
 * @property {string} [gift_note]
 * @property {number} [gift_amount] - currency
 * @property {number} [date_received] - unix timestamp
 * @property {'Bank Transfer'|'Cash'} [donation_type]
 * @property {number} [transfer_date] - unix timestamp
 * @property {boolean} [receipt_issued]
 * @property {number} [donor_information_id] - FK → Contact
 * @property {'New'|'Received'} [gift_notification_status]
 * @property {number} [allocation_member_preference_id] - FK → Organisation
 * @property {number} [date_to] - unix timestamp
 * @property {number} [date_from] - unix timestamp
 * @property {'Approved'|'Declined'|'Requested'} [rff_status]
 * @property {number} [total_funds] - currency
 * @property {number} [category_6_legal] - currency
 * @property {number} [category_9_other] - currency
 * @property {number} [project_remainder] - currency
 * @property {number} [category_2_research] - currency
 * @property {number} [category_7_overseas] - currency
 * @property {number} [category_8_staff_team] - currency
 * @property {number} [mullum_seed_admin_fee] - currency
 * @property {string} [total_funds_break_down]
 * @property {number} [auspice_approval_expiry] - unix timestamp
 * @property {number} [due_date_of_funds_report] - unix timestamp
 * @property {string} [project_campaign_manager]
 * @property {number} [category_5_administration] - currency
 * @property {string} [details_of_how_funds_spent]
 * @property {number} [category_4_campaign_advocacy] - currency
 * @property {number} [category_3_education_information] - currency
 * @property {number} [category_1_on_ground_environmental_remediation] - currency
 * @property {Object} [agenda_item_file]
 * @property {string} [agenda_item_title]
 * @property {'Current'|'Deleted'|'Expired'} [agenda_item_status]
 * @property {number} [board_meeting_date] - unix timestamp
 * @property {string} [link_to_docs_folder] - Url/path
 * @property {string} [agenda_item_description]
 * @property {number} [board_member_submitting_agenda_item_id] - FK → Affiliation
 * @property {string} [board_member_agenda_item_edit_page_url]
 * @property {number} [board_member_agenda_item_edit_page_visits]
 * @property {boolean} [board_member_agenda_item_edit_page_published]
 * @property {number} [board_member_agenda_item_edit_page_unique_visits]
 * @property {string} [support]
 * @property {number} [income_other] - currency
 * @property {number} [total_income] - currency
 * @property {string} [new_project_plans]
 * @property {'Accepted'|'Cancelled'|'More Information Required'|'To Be Reviewed'} [impact_report_status]
 * @property {number} [reporting_year_end_date] - unix timestamp
 * @property {string} [impacts_and_achievements]
 * @property {number} [income_from_other_grants] - currency
 * @property {number} [income_from_bunya_fund_donations_and_grants] - currency
 * @property {string} [impact_report_edit_page_url]
 * @property {number} [impact_report_edit_page_visits]
 * @property {boolean} [impact_report_edit_page_published]
 * @property {number} [impact_report_edit_page_unique_visits]
 * @property {number} [total_minutes]
 * @property {'Completed'|'In Progress'|'New'} [member_support_status]
 */

/**
 * An Invoice (also known as a Transaction) represents the collection of funds to satisfy the amount owed for one or more Purchase records.
 * @typedef {Object} Invoice
 * @property {number} id
 * @property {number} [contact_id] - FK → Contact
 * @property {string} [contact_name]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [external_order_id]
 * @property {boolean} [hidden]
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [last_recharged_at] - unix timestamp
 * @property {string} [offer_data]
 * @property {boolean} [recharge]
 * @property {number} [recharge_attempts]
 * @property {number} [shipping_amount] - currency
 * @property {'Collections'|'Declined'|'Paid'|'Partially Refunded'|'Pending'|'Refunded'|'Voided'|'Written Off'} [status]
 * @property {number} [subtotal] - currency
 * @property {string} [tax_city]
 * @property {number} [tax_city_amount] - currency
 * @property {string} [tax_county]
 * @property {number} [tax_county_amount] - currency
 * @property {string} [tax_postal_code]
 * @property {string} [tax_state]
 * @property {number} [tax_state_amount] - currency
 * @property {string} [template_id] - The ID of the invoice template sent to the contact.
 * @property {number} [total] - currency
 * @property {number} [total_tax] - currency
 */

/**
 * A Subscription represents a recurring Purchase, which includes a trial period, a payment plan, or a subscription. It represents future purchases which have not been realized yet. This is different fro
 * @typedef {Object} Subscription
 * @property {number} id
 * @property {number} [contact_id] - FK → Contact
 * @property {number} [invoice_id] - FK → Invoice
 * @property {number} [product_id] - FK → Product
 * @property {string} [billing_status]
 * @property {number} [cancellation_date] - unix timestamp
 * @property {number} [count] - number of units from last payment date to next payment date
 * @property {number} [created_at] - unix timestamp
 * @property {boolean} [deleted] - true if order has been paid, cancelled, or deleted
 * @property {number} [length_of_subscription_days] - number of days the open order has elapsed
 * @property {number} [next_payment_amount] - currency
 * @property {number} [next_payment_date] - unix timestamp
 * @property {number} [orig_month_date] - unix timestamp
 * @property {number} [overdue_payment_amount] - currency
 * @property {number} [payment_amount] - currency
 * @property {number} [payment_remaining]
 * @property {number} [payments_made] - count of payments made, if recurring
 * @property {number} [payments_total]
 * @property {number} [quantity]
 * @property {'Payment Plan'|'Setup Fee'|'Subscription'} [type]
 * @property {string} [unit]
 */

/**
 * A Purchase represents the completion of a purchase of a Product.
 * @typedef {Object} Purchase
 * @property {number} id
 * @property {number} [contact_id] - FK → Contact
 * @property {number} [invoice_id] - FK → Invoice
 * @property {number} [product_id] - FK → Product
 * @property {number} [subscription_id] - FK → Subscription
 * @property {string} [affiliate_name] - name of affiliate
 * @property {string} [coupon_code] - code from CouponCode record, if used
 * @property {string} [coupon_name]
 * @property {number} [created_at] - unix timestamp
 * @property {string} [description] - product description
 * @property {number} [discount] - currency
 * @property {number} [last_modified_at] - unix timestamp
 * @property {number} [level1_commission_amount] - currency
 * @property {number} [level2_commission_amount] - currency
 * @property {string} [name] - Product name
 * @property {string} [package_id] - The ID of the package the purchase belongs to, if any.
 * @property {number} [price] - currency
 * @property {number} [quantity]
 * @property {string} [sku]
 * @property {'Collections'|'Declined'|'Paid'|'Pending'|'Refunded'|'Voided'|'Written Off'} [status]
 * @property {number} [total_purchase] - currency
 * @property {'One-time purchase'|'Payment plan'|'Subscription'|'Trial payment'} [type]
 */

/**
 * Model metadata for VitalSync SDK queries.
 * Use MODELS.ModelName.sdkName with plugin.switchTo().
 */
var MODELS = {
  Affiliation: {
    sdkName: 'SeednrAffiliation',
    publicName: 'Affiliation',
    fields: [
      'id', 'created_at', 'last_modified_at'
    ],
    detailFields: [
      'created_at', 'last_modified_at'
    ],
  },
  Product: {
    sdkName: 'SeednrProduct',
    publicName: 'Product',
    fields: [
      'id', 'created_at', 'delay_start', 'deleted', 'description', 'download_limit', 
      'download_time_limit', 'external_id', 'internal_name', 'last_modified_at', 'level1', 
      'level2', 'offer_to_affiliates', 'price', 'product_code', 'product_group', 'product_type', 
      'public_name', 'revenue', 'setup_fee', 'setup_fee_date', 'setup_fee_when', 'shipping', 'sku', 
      'subscription_count', 'subscription_fee', 'subscription_unit', 'taxable', 
      'total_purchases_count', 'trial_period_count', 'trial_period_unit', 'trial_price', 'type'
    ],
    detailFields: [
      'created_at', 'delay_start', 'deleted', 'description', 'download_limit', 
      'download_time_limit', 'external_id', 'internal_name', 'last_modified_at', 'level1', 
      'level2', 'offer_to_affiliates', 'price', 'product_code', 'product_group', 'product_type', 
      'public_name', 'revenue', 'setup_fee', 'setup_fee_date', 'setup_fee_when', 'shipping', 'sku', 
      'subscription_count', 'subscription_fee', 'subscription_unit', 'taxable', 
      'total_purchases_count', 'trial_period_count', 'trial_period_unit', 'trial_price', 'type'
    ],
  },
  Tag: {
    sdkName: 'SeednrTag',
    publicName: 'Tag',
    fields: [
      'tag_id', 'name', 'object_type_id'
    ],
    detailFields: [
      'name', 'object_type_id'
    ],
  },
  Message: {
    sdkName: 'SeednrMessage',
    publicName: 'Message',
    fields: [
      'id', 'autosave', 'clicked_count', 'complaints_count', 'created_at', 'from', 'json_data', 
      'last_auto', 'last_modified_at', 'last_save', 'message_body', 'name', 'not_clicked_count', 
      'not_opened_count', 'object_type_id', 'old_resource', 'opened_count', 'plaintext', 
      'reply_to_email', 'resource', 'send_from_email', 'send_out_name', 'send_to', 'sent_count', 
      'site_id', 'spam_score', 'subject', 'transactional_email', 'type', 'unsubscribed_count', 
      'utm_tracking', 'word_wrap_checkbox'
    ],
    detailFields: [
      'autosave', 'clicked_count', 'complaints_count', 'created_at', 'from', 'json_data', 
      'last_auto', 'last_modified_at', 'last_save', 'message_body', 'name', 'not_clicked_count', 
      'not_opened_count', 'object_type_id', 'old_resource', 'opened_count', 'plaintext', 
      'reply_to_email', 'resource', 'send_from_email', 'send_out_name', 'send_to', 'sent_count', 
      'site_id', 'spam_score', 'subject', 'transactional_email', 'type', 'unsubscribed_count', 
      'utm_tracking', 'word_wrap_checkbox'
    ],
  },
  Note: {
    sdkName: 'SeednrNote',
    publicName: 'Note',
    fields: [
      'id', 'Affiliation_id', 'Comm_id', 'Contact_id', 'Organisation_id', 'date_created', 
      'last_modified_at', 'note', 'object_id', 'object_type_id', 'type'
    ],
    detailFields: [
      'Affiliation_id', 'Comm_id', 'Contact_id', 'Organisation_id', 'date_created', 
      'last_modified_at', 'note', 'object_id', 'object_type_id', 'type'
    ],
  },
  Organisation: {
    sdkName: 'SeednrOrganisation',
    publicName: 'Organisation',
    fields: [
      'id', 'xero_id', 'hubspotid', 'last_note', 'unique_id', 'created_at', 'ip_address', 
      'last_activity', 'last_sms_sent', 'profile_image', 'last_email_sent', 'last_call_logged', 
      'last_modified_at', 'last_sms_received', 'last_email_received', 'city', 'name', 'phone', 
      'state', 'address', 'website', 'industry', 'legal_name', 'description', 'postal_code', 
      'facebook_page', 'annual_revenue', 'instagram_name', 'linked_in_page', 'twitter_handle', 
      'reference_number', 'you_tube_channel', 'billing_contact_id', 'primary_contact_id', 
      'number_of_employees', 'reference_number_type', 'logo', 'status', 'date_joined', 
      'current_month', 'profile_summary', 'org_button_image', 'last_xero_invoice', 
      'invoice_creation_status', 'generate_prorata_invoice', 'create_next_annual_invoice', 
      'date_paid_last_membership_fee', 'portal_affiliation_management_url', 
      'portal_affiliation_management_visits', 'portal_affiliation_management_published', 
      'portal_affiliation_management_unique_visits', 'payment_method', 'other_questions', 
      'type_of_organisation', 'date_expressed_interest', 'acknowledge_membership_fee', 
      'description_of_organisation', 'other', 'support_letter', 'authority_to_fundraise', 
      'grant_writing_services', 'access_to_grant_databases', 'project_management_advice', 
      'skill_development_workshops', 'organisational_development_resources', 
      'promotional_support_of_your_activities', 'support_in_forming_a_workers_co_operative', 
      'support_to_become_an_incorporated_association', 
      'marketing_community_engagement_strategy_brainstorm', 
      'potential_discount_on_insurance_coverage_for_volunteers', 
      'support_to_manage_reporting_and_record_keeping_obligations', 
      'a_personalised_segment_on_the_seed_website_that_links_to_your_we', 
      'access_to_grants_and_donations_requiring_dgr_deductible_gift_rec', 
      'exploring_access_to_a_site_at_the_mullum_enterprise_gardens_for_', 
      'i_d_like_my_project_to_become_a_mullum_seed_project_i_m_not_inco', 
      'networking_peer_to_peer_skill_development_with_other_environment', 
      'support_to_register_as_a_charity_and_or_environmental_organisati', 
      'a_intergenerational_equity', 'c_biodiversity_conservation', 'b_the_precautionary_approach', 
      'sustainable_development_object_n_a', 
      'd_supporting_the_relocalisation_of_goods_and_services_within_the', 
      'research_programme_object_n_a', 
      'a_soil_biology_and_the_relationship_between_healthy_ecosystems_a', 
      'b_practices_and_technologies_for_the_rejuvenation_and_improvemen', 
      'c_monitoring_on_site_water_use_and_grey_water_management_to_mini', 
      'd_the_compatibility_of_particular_plants_soil_types_and_climatic', 'b_waste_minimisation', 
      'education_objects_n_a', 'd_water_conservation_and_reuse_systems', 
      'a_the_role_of_soil_health_in_maintaining_sustainable_ecosystems', 
      'g_demonstrate_best_practice_sustainable_design_and_technologies', 
      'c_modelling_a_variety_of_composting_methods_that_utilise_waste_m', 
      'e_the_identification_and_management_of_weed_species_incorporatin', 
      'f_the_sustainable_production_of_food_in_a_manner_that_enhances_t', 
      'application_objects_n_a', 'a_the_enhancement_of_the_natural_environment', 
      'b_the_optimisation_of_environmentally_sustainable_food_productio', 
      'c_community_capacity_building_that_empowers_people_to_integrate_', 
      'd_create_an_inclusive_environment_which_enables_people_of_all_ag', 
      'member_expression_of_interest_url', 'member_expression_of_interest_visits', 
      'member_expression_of_interest_published', 'member_expression_of_interest_unique_visits', 
      'create_qr', 'donation_template', 'member_donation_url', 'biline_donation_page', 
      'content_donation_page', 'donation_page_qr_code', 'external_donation_link', 
      'member_donation_visits', 'background_donation_page', 'member_donation_published', 
      'member_donation_unique_visits', 'gateway_id', 'invoice_id', 'product_id', 'create_gateway', 
      'create_product', 'member_onboarding_url', 'member_onboarding_visits', 
      'member_onboarding_published', 'member_onboarding_unique_visits', 'bsb', 'account', 
      'bank_status', 'sign_wellid', 'signing_url', 'account_name', 'auspiced_by_seed', 
      'donations_status', 'date_start_auspice', 'date_auspice_signed', 'date_expire_auspice', 
      'date_review_auspice', 'project_description', 'donation_receipt_code', 
      'name_of_auspice_project', 'signed_auspice_agreement', 
      're_create_unsigned_agreement_use_sparingly', 'insurance_cover', 'date_end_insurance', 
      'date_start_insurance', 'drive_folderid', 'drive_folder_link', 'create_member_drive_folder', 
      'section_image1', 'section_image2', 'our_purpose_text', 'our_purpose_image1', 
      'our_purpose_image2', 'our_purpose_image3', 'what_you_can_do_cta', 'what_you_can_do_link', 
      'what_you_can_do_text', 'what_we_are_doing_text', 'lower_feature_background', 
      'portal_profile_url', 'portal_profile_visits', 'portal_profile_published', 
      'portal_profile_unique_visits', 'portal_auspice_url', 'portal_auspice_visits', 
      'portal_auspice_published', 'portal_auspice_unique_visits', 'member_gift_notification_url', 
      'member_gift_notification_visits', 'member_gift_notification_published', 
      'member_gift_notification_unique_visits', 'member_needs_and_objects_url', 
      'member_needs_and_objects_visits', 'member_needs_and_objects_published', 
      'member_needs_and_objects_unique_visits', 'portal_rff_url', 'portal_rff_visits', 
      'portal_rff_published', 'portal_rff_unique_visits', 'fund_request_count_all', 
      'fund_request_open_total', 'offline_donations_pending', 'offline_donations_received', 
      'portal_bank_details_url', 'portal_bank_details_visits', 'portal_bank_details_published', 
      'portal_bank_details_unique_visits', 'portal_member_donation_page_edits_url', 
      'portal_member_donation_page_edits_visits', 'portal_member_donation_page_edits_published', 
      'portal_member_donation_page_edits_unique_visits', 'next_board_meeting_date', 
      'next_board_meeting_time', 'board_agenda_item_status', 'portal_impact_reports_url', 
      'portal_impact_reports_visits', 'portal_impact_reports_published', 
      'portal_impact_reports_unique_visits', 'bruns_river_keepers_founding_members', 
      'bruns_river_keepers_partners_supporters', 'seed_northern_rivers_member_donation_url', 
      'seed_northern_rivers_member_donation_visits', 
      'seed_northern_rivers_member_donation_published', 
      'seed_northern_rivers_member_donation_unique_visits', 'menu_link_name', 'show_as_project', 
      'show_as_campaign', 'link_to_content_in_menu'
    ],
    detailFields: [
      'xero_id', 'hubspotid', 'last_note', 'unique_id', 'created_at', 'ip_address', 
      'last_activity', 'last_sms_sent', 'profile_image', 'last_email_sent', 'last_call_logged', 
      'last_modified_at', 'last_sms_received', 'last_email_received', 'city', 'name', 'phone', 
      'state', 'address', 'website', 'industry', 'legal_name', 'description', 'postal_code', 
      'facebook_page', 'annual_revenue', 'instagram_name', 'linked_in_page', 'twitter_handle', 
      'reference_number', 'you_tube_channel', 'billing_contact_id', 'primary_contact_id', 
      'number_of_employees', 'reference_number_type', 'logo', 'status', 'date_joined', 
      'current_month', 'profile_summary', 'org_button_image', 'last_xero_invoice', 
      'invoice_creation_status', 'generate_prorata_invoice', 'create_next_annual_invoice', 
      'date_paid_last_membership_fee', 'portal_affiliation_management_url', 
      'portal_affiliation_management_visits', 'portal_affiliation_management_published', 
      'portal_affiliation_management_unique_visits', 'payment_method', 'other_questions', 
      'type_of_organisation', 'date_expressed_interest', 'acknowledge_membership_fee', 
      'description_of_organisation', 'other', 'support_letter', 'authority_to_fundraise', 
      'grant_writing_services', 'access_to_grant_databases', 'project_management_advice', 
      'skill_development_workshops', 'organisational_development_resources', 
      'promotional_support_of_your_activities', 'support_in_forming_a_workers_co_operative', 
      'support_to_become_an_incorporated_association', 
      'marketing_community_engagement_strategy_brainstorm', 
      'potential_discount_on_insurance_coverage_for_volunteers', 
      'support_to_manage_reporting_and_record_keeping_obligations', 
      'a_personalised_segment_on_the_seed_website_that_links_to_your_we', 
      'access_to_grants_and_donations_requiring_dgr_deductible_gift_rec', 
      'exploring_access_to_a_site_at_the_mullum_enterprise_gardens_for_', 
      'i_d_like_my_project_to_become_a_mullum_seed_project_i_m_not_inco', 
      'networking_peer_to_peer_skill_development_with_other_environment', 
      'support_to_register_as_a_charity_and_or_environmental_organisati', 
      'a_intergenerational_equity', 'c_biodiversity_conservation', 'b_the_precautionary_approach', 
      'sustainable_development_object_n_a', 
      'd_supporting_the_relocalisation_of_goods_and_services_within_the', 
      'research_programme_object_n_a', 
      'a_soil_biology_and_the_relationship_between_healthy_ecosystems_a', 
      'b_practices_and_technologies_for_the_rejuvenation_and_improvemen', 
      'c_monitoring_on_site_water_use_and_grey_water_management_to_mini', 
      'd_the_compatibility_of_particular_plants_soil_types_and_climatic', 'b_waste_minimisation', 
      'education_objects_n_a', 'd_water_conservation_and_reuse_systems', 
      'a_the_role_of_soil_health_in_maintaining_sustainable_ecosystems', 
      'g_demonstrate_best_practice_sustainable_design_and_technologies', 
      'c_modelling_a_variety_of_composting_methods_that_utilise_waste_m', 
      'e_the_identification_and_management_of_weed_species_incorporatin', 
      'f_the_sustainable_production_of_food_in_a_manner_that_enhances_t', 
      'application_objects_n_a', 'a_the_enhancement_of_the_natural_environment', 
      'b_the_optimisation_of_environmentally_sustainable_food_productio', 
      'c_community_capacity_building_that_empowers_people_to_integrate_', 
      'd_create_an_inclusive_environment_which_enables_people_of_all_ag', 
      'member_expression_of_interest_url', 'member_expression_of_interest_visits', 
      'member_expression_of_interest_published', 'member_expression_of_interest_unique_visits', 
      'create_qr', 'donation_template', 'member_donation_url', 'biline_donation_page', 
      'content_donation_page', 'donation_page_qr_code', 'external_donation_link', 
      'member_donation_visits', 'background_donation_page', 'member_donation_published', 
      'member_donation_unique_visits', 'gateway_id', 'invoice_id', 'product_id', 'create_gateway', 
      'create_product', 'member_onboarding_url', 'member_onboarding_visits', 
      'member_onboarding_published', 'member_onboarding_unique_visits', 'bsb', 'account', 
      'bank_status', 'sign_wellid', 'signing_url', 'account_name', 'auspiced_by_seed', 
      'donations_status', 'date_start_auspice', 'date_auspice_signed', 'date_expire_auspice', 
      'date_review_auspice', 'project_description', 'donation_receipt_code', 
      'name_of_auspice_project', 'signed_auspice_agreement', 
      're_create_unsigned_agreement_use_sparingly', 'insurance_cover', 'date_end_insurance', 
      'date_start_insurance', 'drive_folderid', 'drive_folder_link', 'create_member_drive_folder', 
      'section_image1', 'section_image2', 'our_purpose_text', 'our_purpose_image1', 
      'our_purpose_image2', 'our_purpose_image3', 'what_you_can_do_cta', 'what_you_can_do_link', 
      'what_you_can_do_text', 'what_we_are_doing_text', 'lower_feature_background', 
      'portal_profile_url', 'portal_profile_visits', 'portal_profile_published', 
      'portal_profile_unique_visits', 'portal_auspice_url', 'portal_auspice_visits', 
      'portal_auspice_published', 'portal_auspice_unique_visits', 'member_gift_notification_url', 
      'member_gift_notification_visits', 'member_gift_notification_published', 
      'member_gift_notification_unique_visits', 'member_needs_and_objects_url', 
      'member_needs_and_objects_visits', 'member_needs_and_objects_published', 
      'member_needs_and_objects_unique_visits', 'portal_rff_url', 'portal_rff_visits', 
      'portal_rff_published', 'portal_rff_unique_visits', 'fund_request_count_all', 
      'fund_request_open_total', 'offline_donations_pending', 'offline_donations_received', 
      'portal_bank_details_url', 'portal_bank_details_visits', 'portal_bank_details_published', 
      'portal_bank_details_unique_visits', 'portal_member_donation_page_edits_url', 
      'portal_member_donation_page_edits_visits', 'portal_member_donation_page_edits_published', 
      'portal_member_donation_page_edits_unique_visits', 'next_board_meeting_date', 
      'next_board_meeting_time', 'board_agenda_item_status', 'portal_impact_reports_url', 
      'portal_impact_reports_visits', 'portal_impact_reports_published', 
      'portal_impact_reports_unique_visits', 'bruns_river_keepers_founding_members', 
      'bruns_river_keepers_partners_supporters', 'seed_northern_rivers_member_donation_url', 
      'seed_northern_rivers_member_donation_visits', 
      'seed_northern_rivers_member_donation_published', 
      'seed_northern_rivers_member_donation_unique_visits', 'menu_link_name', 'show_as_project', 
      'show_as_campaign', 'link_to_content_in_menu'
    ],
  },
  TagSubscriber: {
    sdkName: 'SeednrTagSubscriber',
    publicName: 'TagSubscriber',
    fields: [
      'id', 'Affiliation_id', 'Comm_id', 'Contact_id', 'Organisation_id', 'tag_id', 'object_id', 
      'object_type_id'
    ],
    detailFields: [
      'Affiliation_id', 'Comm_id', 'Contact_id', 'Organisation_id', 'tag_id', 'object_id', 
      'object_type_id'
    ],
  },
  Contact: {
    sdkName: 'SeednrContact',
    publicName: 'Contact',
    fields: [
      'id', 'fax', 'city', 'role', 'email', 'state', 'title', 'address', 'country', 'profile', 
      'website', 'birthday', 'zip_code', 'address_2', 'last_name', 'company_id', 'first_name', 
      'sms_number', 'company_name', 'office_phone', 'affiliation_count', 'linkedin_profile_url', 
      'i_agree_to_receive_communications_from_mullum_seed_inc', 'spent', 'twitter', 'facebook', 
      'linkedin', 'timezone', 'hubspotid', 'instagram', 'last_note', 'unique_id', 'created_at', 
      'ip_address', 'user_agent', 'last_activity', 'last_sms_sent', 'last_email_sent', 
      'last_call_logged', 'last_modified_at', 'last_sms_received', 'last_email_received', 'gclid', 
      'score', 'priority', 'sales_stage', 'facebook_fbc', 'facebook_fbp', 'ga_client_id', 
      'media_medium', 'ga_session_id', 'referring_page', 'bulk_sms_status', 'bulk_email_status', 
      'ga_session_number', 'members_prospects', 'linked_in_click_id', 'time_since_last_activity', 
      'last_inbound_sms', 'job_title', 'hubspot_comment', 'donation_preference', 'tell_us_more', 
      'profile_image', 'tell_us_more_2', 'how_can_we_help', 'amount', 'member', 'monthly', 
      'once_off', 'gateway_id', 'invoice_id', 'product_id', 'donation_status', 
      'mentorship_interest', 'giving_circle_inspiration', 'last_invoice', 'offline_transfers', 
      'last_charge_amount', 'last_total_invoice_amount', 'total_amount_of_unpaid_transactions', 
      'last_card_type', 'last_cc_status', 'last_card_number_last_4', 'last_card_expiration_date', 
      'last_card_expiration_year', 'last_card_expiration_month', 'lives_on_the_brunswick_river', 
      'plays_on_the_brunswick_r_iver', 'vision_for_the_brunswick_river', 
      'is_keen_to_assist_or_participate_with', 'wishes_to_volunteer_to_assist_the_alliance', 
      'has_the_following_skills_or_experience_that_they_can_offer_to_th', 'insurance', 
      'vendor_name', 'stall_amount', 'payment_status', 'donation_amount', 'stall_selection', 
      'about_your_stall', 'terms_conditions', 'date_signed_terms', 
      'plants_you_sell_options_as_text', 'location_plants_grown_options_as_text', 
      'i_agree_with_all_the_terms_of_service_and_privacy_policy', 'donation_type', 'select_amount', 
      'donation_amounts', 'giving_circle_comment', 'gift_amount', 'gift_message', 'transfer_date', 
      'send_me_email_updates', 'send_me_updates_in_text_messages', 'brunsrk_subscribe', 
      'brunsrk_volunteer', 'brunsrk_membership', 'select_your_intreest', 'boating', 'fishing', 
      'swimming', 'municipality', 'mention_other', 'donating_funds', 'mention_others', 
      'attending_events', 'other_activities', 'other_recreation', 'other_activities_explain', 
      'participating_in_educational_workshops', 'if_the_river_had_a_voice_what_would_it_say', 
      'discussing_a_corporate_partnership_or_sponsorship', 
      'do_you_live_or_work_in_the_brunswick_river_catchment', 
      'learning_more_about_indigenous_connections_to_the_river', 
      'i_m_not_sure_yet_just_keep_me_updated_on_what_is_happening', 
      'which_bruns_riverkeepers_member_group_s_are_you_part_of_if_any', 
      'discussing_my_property_as_a_location_for_tree_planting_and_other', 
      'participating_in_the_healthy_rivers_monitoring_program_and_citiz', 'weed_management', 
      'riparian_revegetation', 'make_a_financial_contribution', 
      'addressing_erosion_of_river_banks', 'fencing_my_creek_to_exclude_grazing', 
      'planting_native_trees_reforestation', 'i_would_like_to_become_a_riverkeeper', 
      'habitat_and_threatened_species_restoration', 
      'undertake_catchment_restoration_works_on_my_property', 
      'i_would_like_my_organization_or_business_to_join_the_riverkeeper', 
      'would_you_like_more_information_on_river_restoration_works_on_yo', 
      'i_would_like_to_volunteer_as_a_researcher', 
      'i_have_the_following_skills_and_capacities_to_offer', 
      'i_would_like_to_volunteer_in_organizing_events_and_admin', 
      'i_am_an_artist_and_would_like_to_perform_or_create_works_for_the', 
      'i_would_like_to_volunteer_for_on_ground_action_tree_planting_or_', 'involvement_type', 
      'ask_amount', 'key_people', 'past_giving', 'follow_up_date', 'type_of_funder', 
      'committed_amount', 'important_to_note', 'engagement_procedure', 'probability_of_success', 
      'funder_area_of_interest', 'program_seeking_funding', 'expected_commitment_date', 
      'philanthropic_engagement_status', 'interactions_with_seed_nr_to_date', 'details', 
      'location', 'date_time', 'upload_photo', 'affiliation_as_active_members', 'lga', 'sector', 
      'source_of_lead', 'contact_re_survey', 'issue_of_interest', 'Total_Donated', 
      'Giving_Circle_Donated', 'date_became_giving_circle_member', 'giving_portal_invoices_url', 
      'giving_portal_invoices_visits', 'giving_portal_invoices_published', 
      'giving_portal_invoices_unique_visits', 'giving_portal_project_voting_url', 
      'giving_portal_project_voting_visits', 'giving_portal_project_voting_published', 
      'giving_portal_project_voting_unique_visits', 'admin', 'voter', 'applicant', 'committee', 
      'grants_app_status', 'grants_app_user_uuid'
    ],
    detailFields: [
      'fax', 'city', 'role', 'email', 'state', 'title', 'address', 'country', 'profile', 'website', 
      'birthday', 'zip_code', 'address_2', 'last_name', 'company_id', 'first_name', 'sms_number', 
      'company_name', 'office_phone', 'affiliation_count', 'linkedin_profile_url', 
      'i_agree_to_receive_communications_from_mullum_seed_inc', 'spent', 'twitter', 'facebook', 
      'linkedin', 'timezone', 'hubspotid', 'instagram', 'last_note', 'unique_id', 'created_at', 
      'ip_address', 'user_agent', 'last_activity', 'last_sms_sent', 'last_email_sent', 
      'last_call_logged', 'last_modified_at', 'last_sms_received', 'last_email_received', 'gclid', 
      'score', 'priority', 'sales_stage', 'facebook_fbc', 'facebook_fbp', 'ga_client_id', 
      'media_medium', 'ga_session_id', 'referring_page', 'bulk_sms_status', 'bulk_email_status', 
      'ga_session_number', 'members_prospects', 'linked_in_click_id', 'time_since_last_activity', 
      'last_inbound_sms', 'job_title', 'hubspot_comment', 'donation_preference', 'tell_us_more', 
      'profile_image', 'tell_us_more_2', 'how_can_we_help', 'amount', 'member', 'monthly', 
      'once_off', 'gateway_id', 'invoice_id', 'product_id', 'donation_status', 
      'mentorship_interest', 'giving_circle_inspiration', 'last_invoice', 'offline_transfers', 
      'last_charge_amount', 'last_total_invoice_amount', 'total_amount_of_unpaid_transactions', 
      'last_card_type', 'last_cc_status', 'last_card_number_last_4', 'last_card_expiration_date', 
      'last_card_expiration_year', 'last_card_expiration_month', 'lives_on_the_brunswick_river', 
      'plays_on_the_brunswick_r_iver', 'vision_for_the_brunswick_river', 
      'is_keen_to_assist_or_participate_with', 'wishes_to_volunteer_to_assist_the_alliance', 
      'has_the_following_skills_or_experience_that_they_can_offer_to_th', 'insurance', 
      'vendor_name', 'stall_amount', 'payment_status', 'donation_amount', 'stall_selection', 
      'about_your_stall', 'terms_conditions', 'date_signed_terms', 
      'plants_you_sell_options_as_text', 'location_plants_grown_options_as_text', 
      'i_agree_with_all_the_terms_of_service_and_privacy_policy', 'donation_type', 'select_amount', 
      'donation_amounts', 'giving_circle_comment', 'gift_amount', 'gift_message', 'transfer_date', 
      'send_me_email_updates', 'send_me_updates_in_text_messages', 'brunsrk_subscribe', 
      'brunsrk_volunteer', 'brunsrk_membership', 'select_your_intreest', 'boating', 'fishing', 
      'swimming', 'municipality', 'mention_other', 'donating_funds', 'mention_others', 
      'attending_events', 'other_activities', 'other_recreation', 'other_activities_explain', 
      'participating_in_educational_workshops', 'if_the_river_had_a_voice_what_would_it_say', 
      'discussing_a_corporate_partnership_or_sponsorship', 
      'do_you_live_or_work_in_the_brunswick_river_catchment', 
      'learning_more_about_indigenous_connections_to_the_river', 
      'i_m_not_sure_yet_just_keep_me_updated_on_what_is_happening', 
      'which_bruns_riverkeepers_member_group_s_are_you_part_of_if_any', 
      'discussing_my_property_as_a_location_for_tree_planting_and_other', 
      'participating_in_the_healthy_rivers_monitoring_program_and_citiz', 'weed_management', 
      'riparian_revegetation', 'make_a_financial_contribution', 
      'addressing_erosion_of_river_banks', 'fencing_my_creek_to_exclude_grazing', 
      'planting_native_trees_reforestation', 'i_would_like_to_become_a_riverkeeper', 
      'habitat_and_threatened_species_restoration', 
      'undertake_catchment_restoration_works_on_my_property', 
      'i_would_like_my_organization_or_business_to_join_the_riverkeeper', 
      'would_you_like_more_information_on_river_restoration_works_on_yo', 
      'i_would_like_to_volunteer_as_a_researcher', 
      'i_have_the_following_skills_and_capacities_to_offer', 
      'i_would_like_to_volunteer_in_organizing_events_and_admin', 
      'i_am_an_artist_and_would_like_to_perform_or_create_works_for_the', 
      'i_would_like_to_volunteer_for_on_ground_action_tree_planting_or_', 'involvement_type', 
      'ask_amount', 'key_people', 'past_giving', 'follow_up_date', 'type_of_funder', 
      'committed_amount', 'important_to_note', 'engagement_procedure', 'probability_of_success', 
      'funder_area_of_interest', 'program_seeking_funding', 'expected_commitment_date', 
      'philanthropic_engagement_status', 'interactions_with_seed_nr_to_date', 'details', 
      'location', 'date_time', 'upload_photo', 'affiliation_as_active_members', 'lga', 'sector', 
      'source_of_lead', 'contact_re_survey', 'issue_of_interest', 'Total_Donated', 
      'Giving_Circle_Donated', 'date_became_giving_circle_member', 'giving_portal_invoices_url', 
      'giving_portal_invoices_visits', 'giving_portal_invoices_published', 
      'giving_portal_invoices_unique_visits', 'giving_portal_project_voting_url', 
      'giving_portal_project_voting_visits', 'giving_portal_project_voting_published', 
      'giving_portal_project_voting_unique_visits', 'admin', 'voter', 'applicant', 'committee', 
      'grants_app_status', 'grants_app_user_uuid'
    ],
  },
  Comm: {
    sdkName: 'SeednrComm',
    publicName: 'Comm',
    fields: [
      'id', 'last_note', 'unique_id', 'created_at', 'ip_address', 'last_activity', 'last_sms_sent', 
      'profile_image', 'last_email_sent', 'last_call_logged', 'last_modified_at', 
      'last_sms_received', 'last_email_received', 'type', 'organisation_id', 'gift_note', 
      'gift_amount', 'date_received', 'donation_type', 'transfer_date', 'receipt_issued', 
      'donor_information_id', 'gift_notification_status', 'allocation_member_preference_id', 
      'date_to', 'date_from', 'rff_status', 'total_funds', 'category_6_legal', 'category_9_other', 
      'project_remainder', 'category_2_research', 'category_7_overseas', 'category_8_staff_team', 
      'mullum_seed_admin_fee', 'total_funds_break_down', 'auspice_approval_expiry', 
      'due_date_of_funds_report', 'project_campaign_manager', 'category_5_administration', 
      'details_of_how_funds_spent', 'category_4_campaign_advocacy', 
      'category_3_education_information', 'category_1_on_ground_environmental_remediation', 
      'agenda_item_file', 'agenda_item_title', 'agenda_item_status', 'board_meeting_date', 
      'link_to_docs_folder', 'agenda_item_description', 'board_member_submitting_agenda_item_id', 
      'board_member_agenda_item_edit_page_url', 'board_member_agenda_item_edit_page_visits', 
      'board_member_agenda_item_edit_page_published', 
      'board_member_agenda_item_edit_page_unique_visits', 'support', 'income_other', 
      'total_income', 'new_project_plans', 'impact_report_status', 'reporting_year_end_date', 
      'impacts_and_achievements', 'income_from_other_grants', 
      'income_from_bunya_fund_donations_and_grants', 'impact_report_edit_page_url', 
      'impact_report_edit_page_visits', 'impact_report_edit_page_published', 
      'impact_report_edit_page_unique_visits', 'total_minutes', 'member_support_status'
    ],
    detailFields: [
      'last_note', 'unique_id', 'created_at', 'ip_address', 'last_activity', 'last_sms_sent', 
      'profile_image', 'last_email_sent', 'last_call_logged', 'last_modified_at', 
      'last_sms_received', 'last_email_received', 'type', 'organisation_id', 'gift_note', 
      'gift_amount', 'date_received', 'donation_type', 'transfer_date', 'receipt_issued', 
      'donor_information_id', 'gift_notification_status', 'allocation_member_preference_id', 
      'date_to', 'date_from', 'rff_status', 'total_funds', 'category_6_legal', 'category_9_other', 
      'project_remainder', 'category_2_research', 'category_7_overseas', 'category_8_staff_team', 
      'mullum_seed_admin_fee', 'total_funds_break_down', 'auspice_approval_expiry', 
      'due_date_of_funds_report', 'project_campaign_manager', 'category_5_administration', 
      'details_of_how_funds_spent', 'category_4_campaign_advocacy', 
      'category_3_education_information', 'category_1_on_ground_environmental_remediation', 
      'agenda_item_file', 'agenda_item_title', 'agenda_item_status', 'board_meeting_date', 
      'link_to_docs_folder', 'agenda_item_description', 'board_member_submitting_agenda_item_id', 
      'board_member_agenda_item_edit_page_url', 'board_member_agenda_item_edit_page_visits', 
      'board_member_agenda_item_edit_page_published', 
      'board_member_agenda_item_edit_page_unique_visits', 'support', 'income_other', 
      'total_income', 'new_project_plans', 'impact_report_status', 'reporting_year_end_date', 
      'impacts_and_achievements', 'income_from_other_grants', 
      'income_from_bunya_fund_donations_and_grants', 'impact_report_edit_page_url', 
      'impact_report_edit_page_visits', 'impact_report_edit_page_published', 
      'impact_report_edit_page_unique_visits', 'total_minutes', 'member_support_status'
    ],
  },
  Invoice: {
    sdkName: 'SeednrInvoice',
    publicName: 'Invoice',
    fields: [
      'id', 'contact_id', 'contact_name', 'created_at', 'external_order_id', 'hidden', 
      'last_modified_at', 'last_recharged_at', 'offer_data', 'recharge', 'recharge_attempts', 
      'shipping_amount', 'status', 'subtotal', 'tax_city', 'tax_city_amount', 'tax_county', 
      'tax_county_amount', 'tax_postal_code', 'tax_state', 'tax_state_amount', 'template_id', 
      'total', 'total_tax'
    ],
    detailFields: [
      'contact_id', 'contact_name', 'created_at', 'external_order_id', 'hidden', 
      'last_modified_at', 'last_recharged_at', 'offer_data', 'recharge', 'recharge_attempts', 
      'shipping_amount', 'status', 'subtotal', 'tax_city', 'tax_city_amount', 'tax_county', 
      'tax_county_amount', 'tax_postal_code', 'tax_state', 'tax_state_amount', 'template_id', 
      'total', 'total_tax'
    ],
  },
  Subscription: {
    sdkName: 'SeednrSubscription',
    publicName: 'Subscription',
    fields: [
      'id', 'contact_id', 'invoice_id', 'product_id', 'billing_status', 'cancellation_date', 
      'count', 'created_at', 'deleted', 'length_of_subscription_days', 'next_payment_amount', 
      'next_payment_date', 'orig_month_date', 'overdue_payment_amount', 'payment_amount', 
      'payment_remaining', 'payments_made', 'payments_total', 'quantity', 'type', 'unit'
    ],
    detailFields: [
      'contact_id', 'invoice_id', 'product_id', 'billing_status', 'cancellation_date', 'count', 
      'created_at', 'deleted', 'length_of_subscription_days', 'next_payment_amount', 
      'next_payment_date', 'orig_month_date', 'overdue_payment_amount', 'payment_amount', 
      'payment_remaining', 'payments_made', 'payments_total', 'quantity', 'type', 'unit'
    ],
  },
  Purchase: {
    sdkName: 'SeednrPurchase',
    publicName: 'Purchase',
    fields: [
      'id', 'contact_id', 'invoice_id', 'product_id', 'subscription_id', 'affiliate_name', 
      'coupon_code', 'coupon_name', 'created_at', 'description', 'discount', 'last_modified_at', 
      'level1_commission_amount', 'level2_commission_amount', 'name', 'package_id', 'price', 
      'quantity', 'sku', 'status', 'total_purchase', 'type'
    ],
    detailFields: [
      'contact_id', 'invoice_id', 'product_id', 'subscription_id', 'affiliate_name', 'coupon_code', 
      'coupon_name', 'created_at', 'description', 'discount', 'last_modified_at', 
      'level1_commission_amount', 'level2_commission_amount', 'name', 'package_id', 'price', 
      'quantity', 'sku', 'status', 'total_purchase', 'type'
    ],
  },
};
